### ISSUE TITLE
OpenConnect (in the official repos) also works

### ISSUE THREAD

**Issue by ids1024** [kaymmm/pulseconnectsecure-arch#1]
Thanks for packaging this (and saving me the trouble of figuring it out myself); it seems to work.

In theory OpenConnect, which is in the official repos, should work instead:

> OpenConnect is an SSL VPN client initially created to support Cisco's AnyConnect SSL VPN. It has since been ported to support the Juniper SSL VPN which is now known as Pulse Connect Secure.

— http://www.infradead.org/openconnect/index.html

I haven't gotten that to work, but I though I might as well mention it in case you (or anyone else) haven't come across it. It might work with the right configuration.

**Comment by ids1024** [comment]
Actually, openconnect does seem to be working; connecting through the NetworkManager GUI wasn't working, but `sudo openconnect --juniper vpn.library.ucdavis.edu` seems to work.

**Comment by kaymmm** [comment]
Wow, thanks for that! I had unsuccessfully tried using openconnect before putting this together, but when I tried again just now it worked fine. Good find!
